export const ALL_PRODUCTS_BEGIN = 'ALL_PRODUCTS_BEGIN';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_FAIL = 'ALL_PRODUCTS_FAIL';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SINGLE_PRODUCT_BEGIN = 'SINGLE_PRODUCT_BEGIN';
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS';
export const SINGLE_PRODUCT_FAIL = 'SINGLE_PRODUCT_FAIL';
